### ISSUE TITLE
v2.0.0 goals

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/java-sdk#71]
I'm going to summarize all the tasks we need to accomplish in order to release the v2.0.0

- [x] Add Retrieve and Rank #25
- [x] Switch from HttpClient to [OkHttp](http://square.github.io/okhttp/)
- [x] Encode `form-urlencoded` requests. (#64, #62)
- [ ] raw responses from services, see #54
- [ ] metadata to responses, similar to #54
- [ ] Add support for custom headers #22

**Comment by germanattanasio** [comment]
closing this since we just released v2.0.0
