### ISSUE TITLE
SDK Generation TODO - Conversation

### ISSUE THREAD

**Issue by lpatino10** [watson-developer-cloud/java-sdk#765]
- [x] SDK needs to be updated to add dialog_nodes feature (no version date update)
- [x] Need to remove “additionalProperties” from messageResponse for generation
- [x] Working on ordering of methods — no functional change
- [x] Hand-coding still required for pagination support
- [x] Need tests for new dialog nodes endpoints

**Comment by lpatino10** [comment]
@mkistler, do you think we're done in terms of Conversation support or are there more things to be added?

**Comment by mkistler** [comment]
I don't think we're completely done because pagination still requires hand-coding.  But until we get changes from the service, or come up with a completely new way to paginate, I don't see that changing.
