### ISSUE TITLE
SDK Generation TODO - Discovery

### ISSUE THREAD

**Issue by lpatino10** [watson-developer-cloud/java-sdk#766]
- [x] SDK needs to be updated to 2017-08-01 version date
- [x] Swagger updates in codegen/conversation in PR #146
- [x] A few hand tweaks to fix codestyle issues not handled by formatter
- [ ] Some hand-coded classes for query responses (this could be improved)
- [x] Need tests for new training data endpoints
- [x] Also need test for passages parameter on query
