### ISSUE TITLE
SDK Generation TODO - Visual Recognition

### ISSUE THREAD

**Issue by lpatino10** [watson-developer-cloud/java-sdk#771]
- [ ] No obvious way to describe multiple file uploads of createClassifier
- [ ] Generated SDK has several issues
  - [ ] Excessive generated models: 45 vs 21 in hand-written SDK
  - [ ] Build errors in getImageMetadata, updateImageMetadata because response does not extend GenericModel
  - [ ] createClassifier will probably need to be hand-coded
